function [methodinfo,structs,enuminfo]=nidaqmx;
%NICAIU Create structures to define interfaces found in 'nidaqmx'.

%This function was generated by loadlibrary.m parser version 1.1.6.22 on Fri Nov  7 18:45:31 2008
%perl options:'nidaqmx.i -outfile=nicaiu.m'
ival={cell(1,0)}; % change 0 to the actual number of functions to preallocate the data.
fcns=struct('name',ival,'calltype',ival,'LHS',ival,'RHS',ival,'alias',ival);
structs=[];enuminfo=[];fcnNum=1;
fcns.name{fcnNum}='DAQmxConnectTerms'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}={'cstring', 'cstring', 'int32'};fcnNum=fcnNum+1;
methodinfo=fcns;
