function updateImageGUI
global state gh

% updateimageGUI.m*****
% Function that will update the image GUI such that the 
% LookUp tables for each channel can be manipuilated independently.
%
% Written By: Thomas Pologruto
% Cold Spring Harbor Labs
% February 5, 2001

for channelCounter = 1:state.init.maximumNumberOfInputChannels
    channelOn = getfield(state.acq, ['imagingChannel' num2str(channelCounter)]);
    maxOn = getfield(state.acq, ['maxImage' num2str(channelCounter)]);
    if channelOn | maxOn
        set([getfield(gh.imageGUI, ['whiteSlideChan' num2str(channelCounter)]) ...
                getfield(gh.imageGUI, ['blackSlideChan' num2str(channelCounter)]) ...
                getfield(gh.imageGUI, ['whiteEditChan' num2str(channelCounter)]) ...
                getfield(gh.imageGUI, ['blackEditChan' num2str(channelCounter)]) ...
                getfield(gh.imageGUI, ['text' num2str(3*channelCounter-2)]) ...
                getfield(gh.imageGUI, ['text' num2str(3*channelCounter-1)]) ...
                getfield(gh.imageGUI, ['zoom' num2str(channelCounter)])...
                getfield(gh.imageGUI, ['imstats' num2str(channelCounter)])...
                getfield(gh.imageGUI, ['histogram' num2str(channelCounter)])...
                getfield(gh.imageGUI, ['label' num2str(channelCounter)])] ...
            , 'Enable', 'On');	
    else
        set([getfield(gh.imageGUI, ['whiteSlideChan' num2str(channelCounter)]) ...
                getfield(gh.imageGUI, ['blackSlideChan' num2str(channelCounter)]) ...
                getfield(gh.imageGUI, ['whiteEditChan' num2str(channelCounter)]) ...
                getfield(gh.imageGUI, ['blackEditChan' num2str(channelCounter)]) ...
                getfield(gh.imageGUI, ['text' num2str(3*channelCounter-2)]) ...
                getfield(gh.imageGUI, ['text' num2str(3*channelCounter-1)]) ...
                getfield(gh.imageGUI, ['zoom' num2str(channelCounter)])...
                getfield(gh.imageGUI, ['imstats' num2str(channelCounter)])...
                getfield(gh.imageGUI, ['histogram' num2str(channelCounter)])...
                getfield(gh.imageGUI, ['label' num2str(channelCounter)])] ...
            , 'Enable', 'Off');
    end
end
